 export const skills = [
    { value: "s1", label: "C#" },
    { value: "s2", label: "C++" },
    { value: "s3", label: "Java" },
    { value: "s4", label: "JavaScript" },
    { value: "s5", label: "Python" },
    { value: "s6", label: "SQL" },
    { value: "s7", label: "React.js" },
    { value: "s8", label: "Angular" },
    { value: "s9", label: "SAP" },
    { value: "s10", label: "Salesforce" },
    { value: "s11", label: "Vue.js" },
    { value: "s12", label: "Angular.js" },
    { value: "s13", label: "Git" },
    { value: "s14", label: "DevOps" },
    { value: "s15", label: "Azure" },
    { value: "s16", label: "AWS" },
    { value: "s17", label: "HTML" },
    { value: "s18", label: "CSS" },
    { value: "s19", label: "PHP" },
    { value: "s20", label: "Ruby" },
    { value: "s21", label: "Swift" },
    { value: "s22", label: "Objective-C" },
    { value: "s23", label: "Kotlin" },
    { value: "s24", label: "R" },
    { value: "s25", label: "Perl" },
    { value: "s26", label: "Shell scripting" },
    { value: "s27", label: "Go" },
    { value: "s28", label: "TypeScript" },
    { value: "s29", label: "Scala" },
    { value: "s30", label: "Haskell" },
    { value: "s31", label: "Lua" },
    { value: "s32", label: "MATLAB" },
    { value: "s33", label: "PowerShell" },
    { value: "s34", label: "MongoDB" },
    { value: "s35", label: "Docker" },
    { value: "s36", label: "Kubernetes" },
    { value: "s37", label: "Jenkins" },
    { value: "s38", label: "Ansible" },
    { value: "s39", label: "Terraform" },
    { value: "s40", label: "Project management" },
    { value: "s41", label: "Agile methodology" },
    { value: "s42", label: "Scrum" },
    { value: "s43", label: "Waterfall methodology" },
    { value: "s44", label: "Lean Six Sigma" },
    { value: "s45", label: "Business analysis" },
    { value: "s46", label: "Data analysis" },
    { value: "s47", label: "Machine learning" },
    { value: "s48", label: "Artificial intelligence" },
    { value: "s49", label: "Big data" },
    { value: "s50", label: "Blockchain" },
    { value: "s51", label: "Ruby on Rails" },
    { value: "s52", label: "Spring framework" },
    { value: "s53", label: "Django" },
    { value: "s54", label: "Flask" },
    { value: "s55", label: "Express.js" },
    { value: "s56", label: "Node.js" },
    { value: "s57", label: "TensorFlow" },
    { value: "s58", label: "Keras" },
    { value: "s59", label: "PyTorch" },
    { value: "s60", label: "Natural Language Processing (NLP)" },
    { value: "s61", label: "Computer vision" },
    { value: "s62", label: "Data mining" },
    { value: "s63", label: "Statistical analysis" },
    { value: "s64", label: "Data visualization" },
    { value: "s65", label: "Deep learning" },
    { value: "s66", label: "Reinforcement learning" },
    { value: "s67", label: "Neural networks" },
    { value: "s68", label: "Computer graphics" },
    { value: "s69", label: "Virtual reality (VR)" },
    { value: "s70", label: "Augmented reality (AR)" },
    { value: "s71", label: "Internet of Things (IoT)" },
    { value: "s72", label: "Blockchain development" },
    { value: "s73", label: "Smart contracts" },
    { value: "s74", label: "Cryptocurrency" },
    { value: "s75", label: "Cybersecurity" },
    { value: "s76", label: "Penetration testing" },
    { value: "s77", label: "Network security" },
    { value: "s78", label: "Web security" },
    { value: "s79", label: "Ethical hacking" },
    { value: "s80", label: "Malware analysis" },
    { value: "s81", label: "Vulnerability assessment" },
    { value: "s82", label: "Risk management" },
    { value: "s83", label: "Artificial neural networks" },
    { value: "s84", label: "Genetic algorithms" },
    { value: "s85", label: "Fuzzy logic" },
    { value: "s86", label: "Expert systems" },
    { value: "s87", label: "Machine vision" },
    { value: "s88", label: "Robotics" },
    { value: "s89", label: "Embedded systems" },
    { value: "s90", label: "Digital signal processing" },
    { value: "s91", label: "Database management" },
    { value: "s92", label: "Data modeling" },
    { value: "s93", label: "Data warehousing" },
    { value: "s94", label: "ETL (Extract, Transform, Load)" },
    { value: "s95", label: "Data governance" },
    { value: "s96", label: "Data quality" },
    { value: "s97", label: "Data integration" },
    { value: "s98", label: "Data migration" },
    { value: "s99", label: "Data privacy" },
    { value: "s100", label: "Data ethics" },
    { value: "s101", label: "Data architecture" },
    { value: "s102", label: "Data analytics" },
    { value: "s103", label: "Data governance" },
    { value: "s104", label: "Data security" },
    { value: "s105", label: "Data storage" },
    { value: "s106", label: "Data retrieval" },
    { value: "s107", label: "Data visualization" },
    { value: "s108", label: "Data mining" },
    { value: "s109", label: "Data engineering" },
    { value: "s110", label: "Data science" },
    { value: "s111", label: "Data exploration" },
    { value: "s112", label: "Data manipulation" },
    { value: "s113", label: "Data preprocessing" },
    { value: "s114", label: "Data cleaning" },
    { value: "s115", label: "Data transformation" },
    { value: "s116", label: "Data validation" },
    { value: "s117", label: "Data analysis" },
    { value: "s118", label: "Data interpretation" },
    { value: "s119", label: "Data-driven decision making" },
    { value: "s120", label: "Data visualization" },
    { value: "s121", label: "Data storytelling" },
    { value: "s122", label: "Data presentation" },
    { value: "s123", label: "Data reporting" },
    { value: "s124", label: "Data-driven insights" },
    { value: "s125", label: "Data analysis tools" },
    { value: "s126", label: "Data analytics software" },
    { value: "s127", label: "Data modeling tools" },
    { value: "s128", label: "Data management systems" },
    { value: "s129", label: "Data integration tools" },
    { value: "s130", label: "Data extraction tools" },
    { value: "s131", label: "Data governance tools" },
    { value: "s132", label: "Data quality tools" },
    { value: "s133", label: "Data storage systems" },
    { value: "s134", label: "Data retrieval tools" },
    { value: "s135", label: "Data visualization tools" },
    { value: "s136", label: "Data mining tools" },
    { value: "s137", label: "Data engineering tools" },
    { value: "s138", label: "Data science tools" },
    { value: "s139", label: "Data analysis techniques" },
    { value: "s140", label: "Data interpretation techniques" },
    { value: "s141", label: "Data-driven decision-making techniques" },
    { value: "s142", label: "Data visualization techniques" },
    { value: "s143", label: "Data storytelling techniques" },
    { value: "s144", label: "Data presentation techniques" },
    { value: "s145", label: "Data reporting techniques" },
    { value: "s146", label: "Data-driven insights techniques" },
    { value: "s147", label: "Data analysis methodologies" },
    { value: "s148", label: "Data interpretation methodologies" },
    { value: "s149", label: "Data-driven decision-making methodologies" },
    { value: "s150", label: "Data visualization methodologies" },
    { value: "s151", label: "Flask" },
    { value: "s152", label: "Spring Boot" },
    { value: "s153", label: "Ruby on Rails" },
    { value: "s154", label: "Laravel" },
    { value: "s155", label: "Express.js" },
    { value: "s156", label: "Vue.js" },
    { value: "s157", label: "React Native" },
    { value: "s158", label: "Flutter" },
    { value: "s159", label: "TensorFlow" },
    { value: "s160", label: "Keras" },
    { value: "s161", label: "PyTorch" },
    { value: "s162", label: "Scikit-learn" },
    { value: "s163", label: "Node.js" },
    { value: "s164", label: "jQuery" },
    { value: "s165", label: "ASP.NET" },
    { value: "s166", label: "ASP.NET Core" },
    { value: "s167", label: "Symfony" },
    { value: "s168", label: "CodeIgniter" },
    { value: "s169", label: "Dart" },
    { value: "s170", label: "Unity" },
    { value: "s171", label: "Unreal Engine" },
    { value: "s172", label: "OpenGL" },
    { value: "s173", label: "Vulkan" },
    { value: "s174", label: "Xamarin" },
    { value: "s175", label: "Qt" },
    { value: "s176", label: "Electron" },
    { value: "s177", label: "WPF" },
    { value: "s178", label: "WinForms" },
    { value: "s179", label: "GTK" },
    { value: "s180", label: "wxWidgets" },
    { value: "s181", label: "CMake" },
    { value: "s182", label: "Makefile" },
    { value: "s183", label: "Gradle" },
    { value: "s184", label: "Jasmin" },
    { value: "s185", label: "Carmen" },
    { value: "s186", label: "Unit Testing" },
    { value: "s187", label: "Nexus" },
    { value: "s188", label: "Sonar" },
    { value: "s189", label: "Jenkins" },
    { value: "s190", label: "Git" },
    { value: "s191", label: "Swagger" },
    { value: "s192", label: "Postman" },
    { value: "s193", label: "SoapUI" },
    { value: "s194", label: "IntelliJ" },
    { value: "s195", label: "Continuous Integration" },
    { value: "s196", label: "SQL" },
    { value: "s197", label: "Postgres" },
    { value: "s198", label: "HTTP Session management and persistence" },
    { value: "s199", label: "HTTP Authentication, and Encryption with SSL" },
    { value: "s200", label: "Json" },
    { value: "s201", label: "XML" },
    { value: "s202", label: "Schemas" },
    { value: "s203", label: "Java Persistence Framework" },
    { value: "s204", label: "Soap Services" },
    { value: "s205", label: "Restful API" },
    { value: "s206", label: "Bootstrap" },
    { value: "s207", label: "Polymer" },
    { value: "s208", label: "Elastic" },
    { value: "s209", label: "AJAX" },
    { value: "s210", label: "html5" },
    { value: "s211", label: "SASS/SCSS" },
    { value: "s212", label: "java 7 & 8+" },
    { value: "s213", label: "MicroService Development" },
    { value: "s214", label: "Apache Kafka" },
    { value: "s215", label: "RabbitMQ" },
    { value: "s216", label: "GraphQL" },
    { value: "s217", label: "Apollo GraphQL" },
    { value: "s218", label: "NestJS" },
    { value: "s219", label: "FastAPI" },
    { value: "s220", label: "Django REST Framework" },
    { value: "s221", label: "Flask-RESTful" },
    { value: "s222", label: "ASP.NET Web API" },
      
 ]


  export const projectTeams =[
    {"value": "projteam0", "label": "I want to develop a brand new system/application"},
    {"value": "projteam1", "label": "I want to add new features to a current system/application."},
    {"value": "projteam2", "label": "I want to scale up an existing development team to speed up development"},
    {"value": "projteam3", "label": "I want to replace my current development team"},
    {"value": "projteam4", "label": "I want to audit a current system/application"},
    {"value": "projteam5", "label": "I want to change the hosting for an existing system/application"}
  ];

  export const noticePeriods =[
    {"value": "nt1", "label": "No notice period"},
    {"value": "nt2", "label": "2 weeks notice period"},
    {"value": "nt3", "label": "1 month notice period"},
    {"value": "nt4", "label": "2 months notice period"}
  ];

  
  export const experience =[
    {"value": "exp1", "label": "This is my first job"},
    {"value": "exp2", "label": "1-2 years experience"},
    {"value": "exp3", "label": "2 - 5 years experience"},
    {"value": "exp4", "label": "5 - 10 years experience"},
    {"value": "exp5", "label": "+10 years experience"},
    
  ];



  export interface IOption{
    value:string,
    label:string
}


  export const techStack=[
    { "value": "s1", "label": "C#" },
    { "value": "s2", "label": "C++" },
    { "value": "s3", "label": "Java" },
    { "value": "s4", "label": "JavaScript" },
    { "value": "s5", "label": "Python" },
    { "value": "s6", "label": "SQL" },
    { "value": "s7", "label": "React.js" },
    { "value": "s8", "label": "Angular" },
    { "value": "s9", "label": "SAP" },
    { "value": "s10", "label": "Salesforce" },
    { "value": "s11", "label": "Vue.js" },
    { "value": "s12", "label": "Angular.js" },
    { "value": "s13", "label": "Git" },
    { "value": "s14", "label": "DevOps" },
    { "value": "s15", "label": "Azure" },
    { "value": "s16", "label": "AWS" },
    { "value": "s17", "label": "HTML" },
    { "value": "s18", "label": "CSS" },
    { "value": "s19", "label": "PHP" },
    { "value": "s20", "label": "Ruby" },
    { "value": "s21", "label": "Swift" },
    { "value": "s22", "label": "Objective-C" },
    { "value": "s23", "label": "Kotlin" },
    { "value": "s24", "label": "R" },
    { "value": "s25", "label": "Perl" },
    { "value": "s26", "label": "Shell scripting" },
    { "value": "s27", "label": "Go" },
    { "value": "s28", "label": "TypeScript" },
    { "value": "s29", "label": "Scala" },
    { "value": "s30", "label": "Haskell" },
    { "value": "s31", "label": "Lua" },
    { "value": "s32", "label": "MATLAB" },
    { "value": "s33", "label": "PowerShell" },
    { "value": "s34", "label": "MongoDB" },
    { "value": "s35", "label": "Docker" },
    { "value": "s36", "label": "Kubernetes" },
  ]

  export const typeOfProject =[
    {"value": "projtype0", "label": "Fin-Tech platform"},
    {"value": "projtype1", "label": "E-commerce platform"},
    {"value": "projtype2", "label": "Marketting website"},
    {"value": "projtype3", "label": "Big Data, ML or AI"},
    {"value": "projtype4", "label": "Technical upgrade of an existing system"},
    {"value": "projtype5", "label": "Healthcare Information System"},
    {"value": "projtype6", "label": "Education Management System"},
    {"value": "projtype7", "label": "Customer Relationship Management (CRM) Software"},
    {"value": "projtype8", "label": "Supply Chain Management System"},
    {"value": "projtype9", "label": "Social Media Platform"},
    {"value": "projtype10", "label": "Mobile App Development (iOS/Android)"},
    {"value": "projtype11", "label": "Gaming Software"},
    {"value": "projtype12", "label": "Internet of Things (IoT) Applications"},
    {"value": "projtype13", "label": "Content Management System (CMS)"},
    {"value": "projtype14", "label": "Virtual Reality (VR) or Augmented Reality (AR) Applications"},
    {"value": "projtype15", "label": "Project Management Software"},
    {"value": "projtype16", "label": "Benchmark Testing & Advisory"},
  ]
  


export const universities =[
    { "value": "u0", "label": "University Of Cape Town", logo:"" },
    { "value": "u1", "label": "University of Johannesburg", logo:"" },
];



export const degrees =
[
    { "value": "c0", "label": "Degree: Bachelor of Science in Computer Science" },
    { "value": "c1", "label": "Degree: Bachelor of Engineering in Software Engineering" },
    { "value": "c2", "label": "Degree: Bachelor of Technology in Information Technology" },
    { "value": "c3", "label": "Degree: Bachelor of Science in Information Systems" },
    { "value": "c4", "label": "Degree: Bachelor of Business Administration in Project Management" },
    { "value": "c5", "label": "Degree: Bachelor of Science in Computer Engineering" },
    { "value": "c6", "label": "Degree: Bachelor of Arts in Web Design and Development" },
    { "value": "c7", "label": "Degree: Bachelor of Science in Data Science" },
    { "value": "c8", "label": "Degree: Bachelor of Science in Cybersecurity" },
    { "value": "c9", "label": "Degree: Bachelor of Science in Network Administration" },
    { "value": "c10", "label": "Postgraduate Degree: Master of Science in Software Engineering" },
    { "value": "c11", "label": "Postgraduate Degree: Master of Science in Information Systems" },
    { "value": "c12", "label": "Postgraduate Degree: Master of Business Administration in Project Management" },
    { "value": "c13", "label": "Postgraduate Degree: Master of Science in Data Analytics" },
    { "value": "c14", "label": "Postgraduate Degree: Master of Science in Cybersecurity" },
    { "value": "c15", "label": "Postgraduate Degree: Master of Technology in IT Management" },
    { "value": "c16", "label": "Postgraduate Degree: Master of Science in Network Security" },
    { "value": "c17", "label": "Diploma: Diploma in Software Development" },
    { "value": "c18", "label": "Diploma: Diploma in Web Design" },
    { "value": "c19", "label": "Diploma: Diploma in Database Administration" },
    { "value": "c20", "label": "Diploma: Diploma in IT Support" },
    { "value": "c21", "label": "SAP Certification: SAP Certified Application Associate - Financial Accounting" },
    { "value": "c22", "label": "SAP Certification: SAP Certified Development Associate - ABAP with SAP NetWeaver" },
    { "value": "c23", "label": "SAP Certification: SAP Certified Technology Associate - System Administration" },
    { "value": "c24", "label": "SAP Certification: SAP Certified Application Associate - Sales and Distribution" },
    { "value": "c25", "label": "SAP Certification: SAP Certified Development Associate - SAP HANA" },
    { "value": "c26", "label": "SAP Certification: SAP Certified Technology Associate - Database Administrator" },
    { "value": "c27", "label": "SAP Certification: SAP Certified Application Associate - Human Capital Management" },
    { "value": "c28", "label": "SAP Certification: SAP Certified Development Associate - Fiori Application Developer" },
    { "value": "c29", "label": "SAP Certification: SAP Certified Technology Associate - Security Consultant" },
    { "value": "c30", "label": "SAP Certification: SAP Certified Application Associate - Procurement" },
    { "value": "c31", "label": "SAP Certification: SAP Certified Development Associate - Cloud Integration" },
    { "value": "c32", "label": "SAP Certification: SAP Certified Technology Associate - System Administrator (Oracle DB)" },
    { "value": "c33", "label": "SAP Certification: SAP Certified Application Associate - Project Manager" },
    { "value": "c34", "label": "SAP Certification: SAP Certified Development Associate - SAPUI5" },
    { "value": "c35", "label": "SAP Certification: SAP Certified Technology Associate - Solution Manager" },
    { "value": "c36", "label": "SAP Certification: SAP Certified Application Associate - Quality Management" },
    { "value": "c37", "label": "SAP Certification: SAP Certified Development Associate - ABAP for SAP HANA" },
    { "value": "c38", "label": "SAP Certification: SAP Certified Technology Associate - Database Administrator (MaxDB)" },
    { "value": "c39", "label": "SAP Certification: SAP Certified Application Associate - Plant Maintenance" },
    { "value": "c40", "label": "SAP Certification: SAP Certified Development Associate - SAP Mobile Platform" },
    { "value": "c41", "label": "SAP Certification: SAP Certified Technology Associate - System Administrator (MS SQL Server)" },
    { "value": "c42", "label": "SAP Certification: SAP Certified Application Associate - Production Planning" },
    { "value": "c43", "label": "SAP Certification: SAP Certified Development Associate - SAP Cloud Platform" },
    { "value": "c44", "label": "SAP Certification: SAP Certified Technology Associate - System Administrator (DB2)" },
    { "value": "c45", "label": "SAP Certification: SAP Certified Application Associate - Customer Service" },
    { "value": "c46", "label": "SAP Certification: SAP Certified Development Associate - Process Integration with SAP NetWeaver" },
    { "value": "c47", "label": "SAP Certification: SAP Certified Technology Associate - System Administrator (Sybase ASE)" },
    { "value": "c48", "label": "SAP Certification: SAP Certified Application Associate - Warehouse Management" },
    { "value": "c49", "label": "SAP Certification: SAP Certified Development Associate - SAP Cloud for Customer" },
    { "value": "c50", "label": "Degree: Master of Science in Information Systems" },
    { "value": "c51", "label": "Degree: Master of Science in Computer Science" },
    { "value": "c52", "label": "Degree: Master of Science in Software Engineering" },
    { "value": "c53", "label": "Degree: Master of Science in Data Science" },
    { "value": "c54", "label": "Degree: Master of Science in Cybersecurity" },
    { "value": "c55", "label": "Degree: Master of Business Administration in Project Management" },
    { "value": "c56", "label": "Degree: Master of Technology in IT Management" },
    { "value": "c57", "label": "Degree: Master of Science in Network Security" },
    { "value": "c58", "label": "Degree: Master of Science in Web Development" },
    { "value": "c59", "label": "Degree: Master of Science in Artificial Intelligence" },
    { "value": "c60", "label": "Degree: Master of Science in Cloud Computing" },
    { "value": "c61", "label": "Degree: Bachelor of Science in Software Testing" },
    { "value": "c62", "label": "Degree: Bachelor of Science in Quality Assurance" },
    { "value": "c63", "label": "Degree: Bachelor of Engineering in Test Automation" },
    { "value": "c64", "label": "Degree: Bachelor of Technology in Software Quality Management" },
    { "value": "c65", "label": "Degree: Bachelor of Science in Project Management" },
    { "value": "c66", "label": "Degree: Bachelor of Science in Agile Methodologies" },
    { "value": "c67", "label": "Degree: Bachelor of Arts in User Acceptance Testing" },
    { "value": "c68", "label": "Degree: Bachelor of Science in Test Planning and Execution" },
    { "value": "c69", "label": "Degree: Bachelor of Business Administration in Software Quality Assurance" },
    { "value": "c70", "label": "Degree: Bachelor of Science in Scrum Master" },
    { "value": "c71", "label": "Degree: Bachelor of Science in Project Quality Control" },
    { "value": "c72", "label": "Degree: Bachelor of Engineering in Performance Testing" },
    { "value": "c73", "label": "Degree: Bachelor of Technology in Test Environment Management" },
    { "value": "c74", "label": "Degree: Bachelor of Science in Risk-Based Testing" },
    { "value": "c75", "label": "Degree: Bachelor of Science in DevOps Testing" },
    { "value": "c76", "label": "Degree: Bachelor of Arts in Security Testing" },
    { "value": "c77", "label": "Degree: Bachelor of Science in Test Automation Frameworks" },
    { "value": "c78", "label": "Degree: Bachelor of Science in Load Testing" },
    { "value": "c79", "label": "Degree: Bachelor of Business Administration in Test Management" },
    { "value": "c80", "label": "Degree: Bachelor of Science in API Testing" },
    { "value": "c81", "label": "Degree: Bachelor of Science in Project Risk Management" },
    { "value": "c82", "label": "Degree: Bachelor of Arts in Agile Project Management" },
    { "value": "c83", "label": "Degree: Bachelor of Science in Quality Control" },
    { "value": "c84", "label": "Degree: Bachelor of Engineering in Configuration Management" },
    { "value": "c85", "label": "Degree: Bachelor of Technology in Defect Management" },
    { "value": "c86", "label": "Degree: Bachelor of Science in Test Reporting and Metrics" },
    { "value": "c87", "label": "Degree: Bachelor of Science in Test Case Design" },
    { "value": "c88", "label": "Degree: Bachelor of Business Administration in Continuous Integration" },
    { "value": "c89", "label": "Degree: Bachelor of Science in Exploratory Testing" },
    { "value": "c90", "label": "Degree: Bachelor of Science in Usability Testing" },
    { "value": "c91", "label": "Degree: Bachelor of Engineering in Test Data Management" },
    { "value": "c92", "label": "Degree: Bachelor of Technology in Security Testing" },
    { "value": "c93", "label": "Degree: Bachelor of Science in Mobile App Testing" },
    { "value": "c94", "label": "Degree: Bachelor of Science in Performance Engineering" },
    { "value": "c95", "label": "Degree: Bachelor of Arts in User Interface Testing" },
    { "value": "c96", "label": "Degree: Bachelor of Science in Test Strategy" },
    { "value": "c97", "label": "Degree: Bachelor of Science in Test Execution" },
    { "value": "c98", "label": "Degree: Bachelor of Business Administration in Quality Assurance" },
    { "value": "c99", "label": "Degree: Bachelor of Science in Project Documentation" },
]
export const courses =[
  
    { "value": "c100", "label": "Certification: AWS Certified Solutions Architect - Associate" },
    { "value": "c101", "label": "Certification: AWS Certified Developer - Associate" },
    { "value": "c102", "label": "Certification: AWS Certified SysOps Administrator - Associate" },
    { "value": "c103", "label": "Certification: AWS Certified DevOps Engineer - Professional" },
    { "value": "c104", "label": "Certification: AWS Certified Solutions Architect - Professional" },
    { "value": "c105", "label": "Certification: AWS Certified Advanced Networking - Specialty" },
    { "value": "c106", "label": "Certification: AWS Certified Security - Specialty" },
    { "value": "c107", "label": "Certification: AWS Certified Machine Learning - Specialty" },
    { "value": "c108", "label": "Certification: AWS Certified Database - Specialty" },
    { "value": "c109", "label": "Certification: Microsoft Certified: Azure Administrator Associate" },
    { "value": "c110", "label": "Certification: Microsoft Certified: Azure Developer Associate" },
    { "value": "c111", "label": "Certification: Microsoft Certified: Azure Security Engineer Associate" },
    { "value": "c112", "label": "Certification: Microsoft Certified: Azure AI Engineer Associate" },
    { "value": "c113", "label": "Certification: Microsoft Certified: Azure Data Engineer Associate" },
    { "value": "c114", "label": "Certification: Microsoft Certified: Azure DevOps Engineer Expert" },
    { "value": "c115", "label": "Certification: Microsoft Certified: Azure Solutions Architect Expert" },
    { "value": "c116", "label": "Certification: Microsoft Certified: Azure AI Fundamentals" },
    { "value": "c117", "label": "Certification: Microsoft Certified: Azure Data Fundamentals" },
    { "value": "c118", "label": "Certification: Microsoft Certified: Azure Security Engineer" },
    { "value": "c119", "label": "Certification: Microsoft Certified: Azure Data Scientist" },
    { "value": "c120", "label": "Certification: Project Management Professional (PMP)" },
    { "value": "c121", "label": "Certification: Certified ScrumMaster (CSM)" },
    { "value": "c122", "label": "Certification: PRINCE2 Practitioner" },
    { "value": "c123", "label": "Certification: Agile Certified Practitioner (PMI-ACP)" },
    { "value": "c124", "label": "Certification: Certified Associate in Project Management (CAPM)" },
    { "value": "c125", "label": "Certification: Certified Project Management Professional (CPMP)" },
    { "value": "c126", "label": "Certification: Certified Scrum Product Owner (CSPO)" },
    { "value": "c127", "label": "Certification: ITIL Foundation Certification" },
    { "value": "c128", "label": "Certification: Certified Information Systems Security Professional (CISSP)" },
    { "value": "c129", "label": "Certification: Certified Ethical Hacker (CEH)" },
    { "value": "c130", "label": "Certification: CompTIA Security+" },
    { "value": "c131", "label": "Certification: Certified Information Privacy Professional (CIPP)" },
    { "value": "c132", "label": "Certification: Certified Cloud Security Professional (CCSP)" },
    { "value": "c133", "label": "Certification: Certified Information Systems Auditor (CISA)" },
    { "value": "c134", "label": "Certification: Certified in Risk and Information Systems Control (CRISC)" },
    { "value": "c135", "label": "Certification: AWS Certified Cloud Practitioner" },
    { "value": "c136", "label": "Certification: AWS Certified Developer - Associate" },
    { "value": "c137", "label": "Certification: AWS Certified SysOps Administrator - Associate" },
    { "value": "c138", "label": "Certification: AWS Certified Solutions Architect - Associate" },
    { "value": "c139", "label": "Certification: AWS Certified DevOps Engineer - Professional" },
    { "value": "c140", "label": "Certification: AWS Certified Solutions Architect - Professional" },
    { "value": "c141", "label": "Certification: AWS Certified Big Data - Specialty" },
    { "value": "c142", "label": "Certification: AWS Certified Advanced Networking - Specialty" },
    { "value": "c143", "label": "Certification: AWS Certified Security - Specialty" },
    { "value": "c144", "label": "Certification: AWS Certified Machine Learning - Specialty" },
    { "value": "c145", "label": "Certification: Google Certified Professional Cloud Architect" },
    { "value": "c146", "label": "Certification: Google Certified Professional Data Engineer" },
    { "value": "c147", "label": "Certification: Google Certified Professional Cloud Developer" },
    { "value": "c148", "label": "Certification: Google Certified Professional Cloud Network Engineer" },
    { "value": "c149", "label": "Certification: Google Certified Professional Cloud Security Engineer" },
    { "value": "c150", "label": "Certification: Google Certified Professional Cloud DevOps Engineer" }
    ]
    
export const roles =[
    {"value": "teammember", "label":"Team member"},
    {"value": "teamlead", "label":"Team Lead"},
    {"value": "projectmanager", "label":"Project manager"},
    {"value": "tester", "label":"Tester"},
    {"value": "testmanager", "label":"Test manager"},
    {"value": "businessanalyst", "label":"Business analyst"},
    {"value": "softwarearchitect", "label":"Software Architect"},
    {"value": "softwaredeveloper", "label":"Software Developer"}
]


export const cities =[
  {"value": "", "label":"Everywhere"},
  {"value": "jhb", "label":"Johannesburg"},
  {"value": "pta", "label":"Pretoria"},
  {"value": "cpt", "label":"Cape Town"},

]


export const provinces =[
    {"value":"gauteng", "label":"Gauteng"},
    {"value":"kwazulunatal", "label":"KwaZulu Natal"},
    {"value":"easterncape", "label":"Eastern Cape"},
    {"value":"westerncape", "label":"Western Cape"},
    {"value":"northerncape", "label":"Northern Cape"},
    {"value":"freestate", "label":"Free state"},
    {"value":"limpopo", "label":"Limpopo"},
    {"value":"northwest", "label":"North West"},
    {"value":"mpumalanga", "label":"Mpumalanga"}
]

export const countries =[
    {"value":"southafrica", "label":"South Africa"}
]

export const allSearchValues = [
    ...skills,
    ...courses,
    ...provinces,
    ...roles,
    ...degrees
  ]

export interface IOption{
    value:string,
    label:string
}

export function getOptionFromValue(value:string[], options:IOption[]):IOption[]{

    const res = value.flatMap(x=>{return options.filter(y=>y.value==x);})
    return res;
  }



  
export function getLabelFromValue(value:string, options:IOption[]):string{

    const res = options.filter(x=>x.value==value)[0];
    return res?.label??"";
  }
